# Exception Handling 
# NameErrorsyntax
# typelogical
# eol
# ValueError


# print("hello")
# print("hello")
# print("hello")
# try:
#     printt("hello")
# except Exception as err:
#     print(err)
# print("hello")




# print("hello")
# try:
#     printt("hello")
# except NameError:
#     print("name is not ")
# print("hello")




# x = int(input("enter"))
# y = int(input("enter"))
# try:
#     print(x/y)
# except Exception as err:
#     print(err)
#     print("i have done ex handling")

# x = int(input("enter"))
# y = int(input("enter"))
# try:
#     z=x/y
#     print("hello working fine")
# except ArithmeticError:
#     print("math error")
#     print("i have done er handling")
# else:
#     print(z)
#     print("i am else method")


a = int(input("enter"))
b = int(input("enter"))

try:
    print(a/b)
    print(c=a/b)
    l =[1,2,3,4,5]
    print(l[2])
except Exception as err:
    print(err)
    print("method execute")
print("exit from error")